Lesson 18: The Badges
georgiybykov/test-guru pull request #35
Opened 2020-12-14 01:24 UTC by georgiybykov

**Разработайте функционал который позволит пользователям получать бэйджи (награды) за успешное прохождение тестов.**

1. Бэйджи представляются моделью `Badge`.
2. Пользователь может получать один и тот же бэйдж более одного раза.
3. Бэйдж обязательно содержит атрибуты:

- Название.
- Имя файла с изображением (Делать загрузку изображений не нужно. Это может быть статический файл с изображением который вручную добавляется в проект. Либо это может быть любой `URL` с изображением бэйджа).

4. Выдача бэйджов происходит автоматически после завершения теста.
5. Управление бэйджами осуществляется администратором.
6. При создании бэйджа администратор также назначает правило, которое определяет порядок выдачи бэйджа. Примеры правил:

- Выдать бэйдж после успешного прохождения всех тестов из категории `Backend`.
- Выдать бэйдж после успешного прохождения теста с первой попытки.
- Выдать бэйдж после успешного прохождения всех тестов определённого уровня.

7. Допускается что критерии правил заданы заранее, например на уровне атрибутов модели.
8. Пользователь в любой момент времени может посмотреть список всех существующих и заработанных бэйджей.

2021-01-11 12:37 UTC, VidgarVii requested changes

2021-01-11 12:37 UTC, VidgarVii commented on app/repositories/test_passage_repository.rb
> +end
вот смотрю я на этот класс и понимаю, что это просто обертка над АР. Который надо тестить и  как-то понять для чего ж он тут нужен.  Для получения каких-то данных из БД и их сериализацию, то тут уже отвечает паттерн АР. 
А вот для инкапсуляции получения данных согласно ДДД, то тут уже спорный вопрос. Который в каком-то году поднимался. И по моему ни к чему хорошему так и не привел...
Для каких-то сложных запросов чаще используют QueryObject. 
Для подготовки данных к какому-то ввиду презентёры/декораторы/сериалайзеры/селы. Для получения коллекций согласно спецификациям - Спецификации... 
А тут что?) 
Но пролистав твой код ниже. Видно, что данный класс используется для создания логики правил получения наград. При этом код который решает эту задачу — Правило у тебя размазан м/у репой и сервиом по выдачи наград. Так вот, тут выстреливает паттерн Контракты =) Ну ни как не репозиторий.. 
Честно говоря я ни разу не видел использования паттерна Репы в Рэйльс и вообще в руби проектах. Мб из-за специфики веб и большого кол-во гемов для веб разработки. А в java или в C# да.

2021-01-11 21:08 UTC, georgiybykov commented on app/helpers/tests_helper.rb
> +    category ? category.title : '< undefined >'
Возможно было такое.
Я добавил валидацию на уровне модели и констрэйнт на уровне БД.
В итоге просто дропнул этот метод.

p.s. сэйф-навигэйшн - зло)))
в этом случае было бы нормально, но в целом его лучше не использовать

2021-01-11 21:10 UTC, georgiybykov commented on app/helpers/tests_helper.rb
>    # end
В курсе)))
Это ж учебный проект, поэтому нужные, на мой взгляд, отрывки кода я оставлял.
Сейчас этот удалил - не несет никакой пользы :+1:

2021-01-11 21:30 UTC, georgiybykov commented on app/mailers/tests_mailer.rb
> +    badges
О, интересно. Спасибо!

Это не релэйшн, просто массив объектов.
Я так понял на релейшене `pluck()` будет на каждую запись запрос в БД отправлять - поэтому ты уточнил.

2021-01-11 21:37 UTC, georgiybykov commented on app/models/test.rb
> +      .order(title: :desc)
О, класс! Спасибо, что указал референс на стайл-гайд - не знал об этом.

Помню, что конкретно по этому скоупу было в самом начале такое задание: "создайте скоуп...". Поэтому он такой...ну и еще я не знал тогда об этом пункте из стайл-гайда)

Исправил

2021-01-11 22:40 UTC, georgiybykov commented on app/controllers/test_passages_controller.rb
> +      new_badges = Badges::AssignBadgesService.new(test_passage: @test_passage, current_user: current_user).call
Мои размышления:

> Этот сервис это `immutable callable object` с `single responsibility`.
> Метод `call` должен сказать только лишь об этом (по хорошему в него и нужно передать аргументами `test_passage` и `current_user`, но я не придумал как их прокидывать внутри сервиса из-за того, что заюзал `send()`).
> О том, что сервис вернет массив бэйджей или `false` написано в комментарии в самом сервисе или можно понять по локальной переменной, в которую присваивается результат.
> Из того, что я написал о методе `call`, который в сервисе один публичный, значение сервиса следует из его названия. `AssignBadgesService` - принимает данные на вход и внутри себя проверяет можно ли присвоить бэйджи пользователю. Либо присваивает, либо нет, а что происходит внутри нас по сути не должно интересовать. Сервис должен выполнить свою единственную ответственность.

К слову, вызов такого сервиса в юнит тесте можно замокать просто через лямбду:)

_Вполне возможно, что с нэймингом самого сервиса у меня здесь проблемка и он не отразил всю суть_
_________________________________________________________________________________________________

> стоит и метод назвать соответствующи.

Не спорю с этим, если мои размышления не верны, но хочу услышать твои аргументы после того, когда прочитаешь мой комментарий.

> А call обычно используют для получения какого-то результата, который далее можно разбить

Такого не встречал, но это точно не единственный вариант. Может ты имеешь в виду сделать матчинг результата и в случае, пусть условно, `success` сделать что-то одно далее, а в случае `failure` что-то иное **??**

> Или просто вызова какого-то действия.

По сути у меня здесь и происходит "вызов какого-то действия")))

2021-01-11 23:02 UTC, georgiybykov commented on app/repositories/test_passage_repository.rb
> +end
> Честно говоря я ни разу не видел использования паттерна Репы в Рэйльс и вообще в руби проектах

Я видел :DDD
___________________________________________________________________________________________

Не буду расписывать все поинты, а лишь пару слов. Мне легче сейчас просто дропнуть этот класс и вернуть эти запросы в сервис по выдаче бэйджев:)

В данный момент ты видишь просто репу, в которой каждый метод обращается к БД и возвращает какой-то результат "специфический". Каждый такой метод можно переиспользовать в другом месте в приложении, легко написать тест на каждый метод такого класса, потом легко замокать вызов такого метода репозитория при юнит тестировании сервисов, в которых ты его вызываешь и т.д.

Обычно этот паттерн юзают для более сложных вещей, чтобы действительно навернуть обертку над AR и использовать уже `entities` и т.д. Короче, чтобы накинуть `accidental complexity` и проблем на будущее, но данный репозиторий отнюдь не об этом)))

______________________________________________________________________________________________

> для создания логики правил получения наград.

Неа, это ж просто запросы в БД, которые нужны в сервисе. Ну я выше описал собственно )

> Так вот, тут выстреливает паттерн Контракты =)

Можешь кинуть в меня ссылкой на такой паттерн, пожалуйста? Желательно в руби/рельсы контексте использования. Че-то я не смог точно нагуглить, чтобы понять о чем именно ты

2021-01-12 06:32 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +      new_badges = Badges::AssignBadgesService.new(test_passage: @test_passage, current_user: current_user).call
единственное что я хочу сказать, что по названию метода (call) не понятно, что он вернет баджы. Название метода плохое. И я тебе дал пару примеров, где данное название приемлемо. Далее решать тебе, что со всем этим делать. Код должен быть читаем и очевиден.

2021-01-12 06:44 UTC, VidgarVii commented on app/repositories/test_passage_repository.rb
> +end
При проектировании классов не надо забывать про отношение объектов целое-часть. Которые решают конкретно одну задачу. А тут репа, ну что бы просто была. Её важность очень сомнительна. На этом задании точно. Теже методы модно было бы положить в модели. И не плохо бы это всё смотрелось, даже в рамках АР. И делай сними что хочешь, переопределяй, мокай и пр. Вопрос, а понадобиться ли?

2021-01-12 06:49 UTC, VidgarVii commented on app/repositories/test_passage_repository.rb
> +end
паттерн Контракты - Контрактное программирование. Это я не много темой промахнулся. Всё же имел ввиду паттерн Спецификации. 
Когда реализуешь инварианты объекта.  Можно почитать например в темах про экстремальное программирование и защитное программирование. Без этого ни как в статичных ЯП. В руби контракты можно реализовать например через dry-rb validation. Валидации в АР теже контракты. Контрактами ты как бы задаешь постусловия клиенту.
Или же часто используется в паттерна Form object. Те же контракты

2021-01-12 06:56 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +      new_badges = Badges::AssignBadgesService.new(test_passage: @test_passage, current_user: current_user).call
сервис выдачи наград на SRP тоже не очень тянет

2021-01-13 07:21 UTC, georgiybykov commented on app/repositories/test_passage_repository.rb
> +end
Спасибо за информацию 👍

2021-01-13 10:54 UTC, VidgarVii requested changes

2021-01-13 10:54 UTC, VidgarVii commented on app/helpers/tests_helper.rb
>    end
очень странный код.. 
Во первых тут хорошо бы встал перечисляемый тип данных ENUM
https://api.rubyonrails.org/v5.2.3/classes/ActiveRecord/Enum.html
Во 2 почему hero не в списке? Вроде логично его видеть в коллекции. 
В 3 данная логика больше относится к описанию объекта Тест. А не к хелперу представления. Да и контенту место в локали

2021-01-13 10:54 UTC, VidgarVii commented on app/models/badge.rb
> +  }
тут тоже хорошо подойдет ENUM и не придется ни чего валидировать

2021-01-13 10:54 UTC, VidgarVii commented on app/services/badges/assign_badges_service.rb
> +    end
запросом fetch_assigned_badges мы вроде как ожидаем получить коллекцию заработанных баджиков. Даже если ни чего не заработали, коллекция всё ровно должна быть, так как данным методом мы что-то требуем во множественном числе. И это вроде логично. В данном случаи массив. И с этим массивом можно будет работать, как с массивом, даже если он будет пуст. Методы итераторы не выбросят исключение. А у тебя метод может вернуть false. И это уже инвариант, который может привести к ошибке. И не надо будет ставить лишние проверки

2021-01-13 10:54 UTC, VidgarVii commented on app/services/badges/assign_badges_service.rb
> +                           .for_user(user.id)
for_user(user.id)
для юзера 1
как то странно звучит. Было бы логично передовать аргументом сам объект юзера

2021-01-13 10:54 UTC, VidgarVii commented on app/services/badges/assign_badges_service.rb
> +                           .where("tests.level": test_level)
where(tests: { level: test_level })

2021-01-15 12:16 UTC, georgiybykov commented on app/services/badges/assign_badges_service.rb
> +    end
Логичное замечание, спасибо

2021-01-15 12:21 UTC, georgiybykov commented on app/services/badges/assign_badges_service.rb
> +                           .for_user(user.id)
Я просто переименовал скоуп в `by_user_id(user_id)`. Если предполагать, что скоуп можно использовать универсально в любом месте проекта, то где-то может не оказаться объекта юзера, но быть `user_id` параметр.

2021-01-15 12:22 UTC, georgiybykov commented on app/helpers/tests_helper.rb
>    end
> очень странный код..

Так легаси же)))

Переделал, но без миграций на создание `pg_enum` значений в БД

2021-01-15 18:10 UTC, VidgarVii commented on app/models/test.rb
> +  }.freeze
в символах наща сила)

2021-01-17 22:56 UTC, georgiybykov commented on app/models/test.rb
> +  }.freeze
Понял-принял)

2021-01-17 22:57 UTC, merged